api:
    insecure: false
    dashboard: true
    debug: true

log:
    level: DEBUG

entryPoints:
    http:
        address: ":80"

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
